import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        agentbase: {
          bg:             "var(--ab-bg)",
          surface:        "var(--ab-surface)",
          card:           "var(--ab-card)",
          cardHover:      "var(--ab-card-hover)",
          canvasBg:       "var(--ab-canvas-bg)",
          border:         "var(--ab-border)",
          borderStrong:   "var(--ab-border-strong)",
          borderSubtle:   "var(--ab-border-subtle)",
          text:           "var(--ab-text)",
          muted:          "var(--ab-text-secondary)",
          tertiary:       "var(--ab-text-tertiary)",
          textMuted:      "var(--ab-text-muted)",
          placeholder:    "var(--ab-text-placeholder)",
          heading:        "var(--ab-heading)",
          cyan:           "var(--ab-accent)",
          cyanGlow:       "var(--ab-accent-glow)",
          yellow:         "var(--ab-yellow)",
          cursor:         "var(--ab-typing-cursor)",
          accentText:     "var(--ab-accent-text)",
          invertedBg:     "var(--ab-inverted-bg)",
          invertedText:   "var(--ab-inverted-text)",
          invertedHover:  "var(--ab-inverted-hover)",
          btnSecBg:       "var(--ab-btn-secondary-bg)",
          btnSecText:     "var(--ab-btn-secondary-text)",
          btnSecBorder:   "var(--ab-btn-secondary-border)",
          btnSecHover:    "var(--ab-btn-secondary-hover)",
          pillBg:         "var(--ab-pill-bg)",
          pillText:       "var(--ab-pill-text)",
          badgeBg:        "var(--ab-badge-bg)",
          badgeText:      "var(--ab-badge-text)",
          cardBoxBg:      "var(--ab-card-box-bg)",
          cardBoxText:    "var(--ab-card-box-text)",
          cardBoxMuted:   "var(--ab-card-box-muted)",
          cardBoxInnerBg: "var(--ab-card-box-inner-bg)",
          cardBoxInnerText: "var(--ab-card-box-inner-text)",
          glassInputBg:   "var(--ab-glass-input-bg)",
          glassInputHover:"var(--ab-glass-input-bg-hover)",
          glassIconBg:    "var(--ab-glass-icon-bg)",
          glassIconBorder:"var(--ab-glass-icon-border)",
        },
      },
      fontFamily: {
        sans: ["'Neue Haas Grotesk'", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
        serif: ["Zarathustra", "serif"],
      },
      backgroundImage: {
        'grid-pattern': "linear-gradient(to right, var(--ab-border) 1px, transparent 1px), linear-gradient(to bottom, var(--ab-border) 1px, transparent 1px)",
      },
    },
  },
  plugins: [],
} satisfies Config;
